Repository B5-outsourcing/shoppingmall, pull requests merged in 2024-06, with the labels that each got.

#30 Feature/#8cart crud
  .github/PULL_REQUEST_TEMPLATE.md
  src/main/java/com/sparta/shoppingmall/cart/controller/CartController.java
  src/main/java/com/sparta/shoppingmall/cart/dto/CartProductRequest.java
  src/main/java/com/sparta/shoppingmall/cart/dto/CartProductResponse.java
  src/main/java/com/sparta/shoppingmall/cart/dto/CartResponse.java
  src/main/java/com/sparta/shoppingmall/cart/entity/Cart.java
  src/main/java/com/sparta/shoppingmall/cart/entity/CartProduct.java
  src/main/java/com/sparta/shoppingmall/cart/repository/CartProductRepository.java
  src/main/java/com/sparta/shoppingmall/cart/repository/CartRepository.java
  src/main/java/com/sparta/shoppingmall/cart/service/CartService.java
Labels: feature

#31 [Feature] #8cart crud
  src/main/java/com/sparta/shoppingmall/cart/controller/CartController.java
  src/main/java/com/sparta/shoppingmall/cart/dto/CartProductRequest.java
  src/main/java/com/sparta/shoppingmall/cart/dto/CartProductResponse.java
  src/main/java/com/sparta/shoppingmall/cart/dto/CartResponse.java
  src/main/java/com/sparta/shoppingmall/cart/entity/Cart.java
  src/main/java/com/sparta/shoppingmall/cart/entity/CartProduct.java
  src/main/java/com/sparta/shoppingmall/cart/repository/CartProductRepository.java
  src/main/java/com/sparta/shoppingmall/cart/repository/CartRepository.java
  src/main/java/com/sparta/shoppingmall/cart/service/CartService.java
Labels: feature

#36 Feature/#32like
  src/main/java/com/sparta/shoppingmall/like/controller/LikesController.java
  src/main/java/com/sparta/shoppingmall/like/dto/LikesRequest.java
  src/main/java/com/sparta/shoppingmall/like/dto/LikesResponse.java
  src/main/java/com/sparta/shoppingmall/like/entity/ContentType.java
  src/main/java/com/sparta/shoppingmall/like/entity/LikeStatus.java
  src/main/java/com/sparta/shoppingmall/like/entity/Likes.java
  src/main/java/com/sparta/shoppingmall/like/repository/LikesRepository.java
  src/main/java/com/sparta/shoppingmall/like/service/LikesService.java
  src/test/java/com/sparta/shoppingmall/ShoppingmallApplicationTests.java
Labels: feature

#37 Feature/#32like
  src/main/java/com/sparta/shoppingmall/like/controller/LikesController.java
  src/main/java/com/sparta/shoppingmall/like/dto/LikesRequest.java
  src/main/java/com/sparta/shoppingmall/like/dto/LikesResponse.java
  src/main/java/com/sparta/shoppingmall/like/entity/ContentType.java
  src/main/java/com/sparta/shoppingmall/like/entity/LikeStatus.java
  src/main/java/com/sparta/shoppingmall/like/entity/Likes.java
  src/main/java/com/sparta/shoppingmall/like/repository/LikesRepository.java
  src/main/java/com/sparta/shoppingmall/like/service/LikesService.java
Labels: feature

#43 Refactor : Order에 대한 기능 리팩토링
  src/main/java/com/sparta/shoppingmall/order/controller/OrderController.java
  src/main/java/com/sparta/shoppingmall/order/controller/OrderGroupController.java
  src/main/java/com/sparta/shoppingmall/order/dto/OrderGroupRequestDto.java
  src/main/java/com/sparta/shoppingmall/order/dto/OrderGroupResponseDto.java
  src/main/java/com/sparta/shoppingmall/order/dto/OrderListResponseDto.java
  src/main/java/com/sparta/shoppingmall/order/dto/OrderRequestDto.java
  src/main/java/com/sparta/shoppingmall/order/dto/OrderResponseDto.java
  src/main/java/com/sparta/shoppingmall/order/entity/Order.java
  src/main/java/com/sparta/shoppingmall/order/entity/OrderGroup.java
  src/main/java/com/sparta/shoppingmall/order/entity/OrderStatus.java
  src/main/java/com/sparta/shoppingmall/order/repository/OrderGroupRepository.java
  src/main/java/com/sparta/shoppingmall/order/repository/OrderRepository.java
  src/main/java/com/sparta/shoppingmall/order/service/OrderGroupService.java
  src/main/java/com/sparta/shoppingmall/order/service/OrderService.java
  src/main/java/com/sparta/shoppingmall/order/status/OrderStatus.java
Labels: refactor

#44 Refactor : 세부적인 내용 수정
  src/main/java/com/sparta/shoppingmall/cart/entity/Cart.java
  src/main/java/com/sparta/shoppingmall/order/entity/OrderGroup.java
Labels: refactor

#45 [FEATURE] User CRUD , Security, JWT
  build.gradle
  src/main/java/com/sparta/shoppingmall/config/JpaConfig.java
  src/main/java/com/sparta/shoppingmall/config/SecurityConfig.java
  src/main/java/com/sparta/shoppingmall/jwt/JwtProvider.java
  src/main/java/com/sparta/shoppingmall/jwt/RefreshToken.java
  src/main/java/com/sparta/shoppingmall/jwt/RefreshTokenRepository.java
  src/main/java/com/sparta/shoppingmall/jwt/RefreshTokenService.java
  src/main/java/com/sparta/shoppingmall/security/JwtAuthenticationFilter.java
  src/main/java/com/sparta/shoppingmall/security/JwtAuthorizationFilter.java
  src/main/java/com/sparta/shoppingmall/security/UserDetailsImpl.java
  src/main/java/com/sparta/shoppingmall/security/UserDetailsServiceImpl.java
  src/main/java/com/sparta/shoppingmall/user/controller/UserController.java
  src/main/java/com/sparta/shoppingmall/user/dto/EditPasswordRequestDTO.java
  src/main/java/com/sparta/shoppingmall/user/dto/EditProfileRequestDTO.java
  src/main/java/com/sparta/shoppingmall/user/dto/EditProfileResponseDTO.java
  src/main/java/com/sparta/shoppingmall/user/dto/LoginRequestDTO.java
  src/main/java/com/sparta/shoppingmall/user/dto/SignupRequestDTO.java
  src/main/java/com/sparta/shoppingmall/user/dto/SignupResponseDTO.java
  src/main/java/com/sparta/shoppingmall/user/dto/UserResponseDTO.java
  src/main/java/com/sparta/shoppingmall/user/dto/WithdrawRequestDTO.java
  src/main/java/com/sparta/shoppingmall/user/entity/User.java
  src/main/java/com/sparta/shoppingmall/user/entity/UserStatus.java
  src/main/java/com/sparta/shoppingmall/user/entity/UserType.java
  src/main/java/com/sparta/shoppingmall/user/exception/UserException.java
  src/main/java/com/sparta/shoppingmall/user/repository/UserRepository.java
  src/main/java/com/sparta/shoppingmall/user/service/UserService.java
Labels: feature

#48 [FEATURE] Product CRUD #47
  src/main/java/com/sparta/shoppingmall/ShoppingmallApplication.java
  src/main/java/com/sparta/shoppingmall/base/entity/Timestamped.java
  src/main/java/com/sparta/shoppingmall/cart/entity/CartProduct.java
  src/main/java/com/sparta/shoppingmall/order/dto/OrderGroupResponseDto.java
  src/main/java/com/sparta/shoppingmall/order/dto/OrderListResponseDto.java
  src/main/java/com/sparta/shoppingmall/order/entity/OrderGroup.java
  src/main/java/com/sparta/shoppingmall/order/entity/Orders.java
  src/main/java/com/sparta/shoppingmall/order/repository/OrderGroupRepository.java
  src/main/java/com/sparta/shoppingmall/order/service/OrderGroupService.java
  src/main/java/com/sparta/shoppingmall/product/controller/ProductController.java
  src/main/java/com/sparta/shoppingmall/product/dto/ProductRequest.java
  src/main/java/com/sparta/shoppingmall/product/dto/ProductResponse.java
  src/main/java/com/sparta/shoppingmall/product/dto/ProductUpdateRequest.java
  src/main/java/com/sparta/shoppingmall/product/entity/Product.java
  src/main/java/com/sparta/shoppingmall/product/entity/ProductStatus.java
  src/main/java/com/sparta/shoppingmall/product/repository/ProductRepository.java
  src/main/java/com/sparta/shoppingmall/product/service/ProductService.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: feature

#51 Refactor : Product 리팩토링
  src/main/java/com/sparta/shoppingmall/product/controller/ProductController.java
  src/main/java/com/sparta/shoppingmall/product/dto/ProductRequest.java
  src/main/java/com/sparta/shoppingmall/product/dto/ProductResponse.java
  src/main/java/com/sparta/shoppingmall/product/dto/ProductUpdateRequest.java
  src/main/java/com/sparta/shoppingmall/product/entity/Product.java
  src/main/java/com/sparta/shoppingmall/product/entity/ProductStatus.java
  src/main/java/com/sparta/shoppingmall/product/repository/ProductRepository.java
  src/main/java/com/sparta/shoppingmall/product/service/ProductService.java
Labels: refactor

#52 [REFACTOR] User, Security 리팩토링
  src/main/java/com/sparta/shoppingmall/base/dto/CommonResponse.java
  src/main/java/com/sparta/shoppingmall/cart/controller/CartController.java
  src/main/java/com/sparta/shoppingmall/cart/entity/Cart.java
  src/main/java/com/sparta/shoppingmall/config/SecurityConfig.java
  src/main/java/com/sparta/shoppingmall/jwt/JwtProvider.java
  src/main/java/com/sparta/shoppingmall/jwt/RefreshToken.java
  src/main/java/com/sparta/shoppingmall/jwt/RefreshTokenService.java
  src/main/java/com/sparta/shoppingmall/like/controller/LikesController.java
  src/main/java/com/sparta/shoppingmall/like/entity/Likes.java
  src/main/java/com/sparta/shoppingmall/order/controller/OrderGroupController.java
  src/main/java/com/sparta/shoppingmall/order/entity/OrderGroup.java
  src/main/java/com/sparta/shoppingmall/product/controller/ProductController.java
  src/main/java/com/sparta/shoppingmall/security/JwtAuthenticationFilter.java
  src/main/java/com/sparta/shoppingmall/security/JwtAuthorizationFilter.java
  src/main/java/com/sparta/shoppingmall/security/UserDetailsImpl.java
  src/main/java/com/sparta/shoppingmall/security/UserDetailsServiceImpl.java
  src/main/java/com/sparta/shoppingmall/user/controller/UserController.java
  src/main/java/com/sparta/shoppingmall/user/dto/EditPasswordRequestDTO.java
  src/main/java/com/sparta/shoppingmall/user/dto/EditProfileRequestDTO.java
  src/main/java/com/sparta/shoppingmall/user/dto/EditProfileResponseDTO.java
  src/main/java/com/sparta/shoppingmall/user/dto/LoginRequestDTO.java
  src/main/java/com/sparta/shoppingmall/user/dto/SignupRequestDTO.java
  src/main/java/com/sparta/shoppingmall/user/dto/SignupResponseDTO.java
  src/main/java/com/sparta/shoppingmall/user/dto/UserResponseDTO.java
  src/main/java/com/sparta/shoppingmall/user/dto/WithdrawRequestDTO.java
  src/main/java/com/sparta/shoppingmall/user/entity/User.java
  src/main/java/com/sparta/shoppingmall/user/entity/UserStatus.java
  src/main/java/com/sparta/shoppingmall/user/entity/UserType.java
  src/main/java/com/sparta/shoppingmall/user/repository/UserRepository.java
  src/main/java/com/sparta/shoppingmall/user/service/UserService.java
  src/main/java/com/sparta/shoppingmall/util/ControllerUtil.java
Labels: refactor

#63 [FEATURE] Comment CURD
  src/main/java/com/sparta/shoppingmall/comment/controller/CommentController.java
  src/main/java/com/sparta/shoppingmall/comment/dto/CommentRequest.java
  src/main/java/com/sparta/shoppingmall/comment/dto/CommentResponse.java
  src/main/java/com/sparta/shoppingmall/comment/entity/Comment.java
  src/main/java/com/sparta/shoppingmall/comment/repository/CommentRepository.java
  src/main/java/com/sparta/shoppingmall/comment/service/CommentService.java
  src/main/java/com/sparta/shoppingmall/product/entity/Product.java
  src/main/java/com/sparta/shoppingmall/product/service/ProductService.java
  src/main/java/com/sparta/shoppingmall/user/entity/User.java
Labels: feature, refactor

#65 Refactor/#56 product delete
  src/main/java/com/sparta/shoppingmall/error/exception/UserMismatchException.java
  src/main/java/com/sparta/shoppingmall/product/controller/ProductController.java
  src/main/java/com/sparta/shoppingmall/product/service/ProductService.java
Labels: refactor

#68 refactor : 패키지명 변경
  src/main/java/com/sparta/shoppingmall/exception/UserMismatchException.java
  src/main/java/com/sparta/shoppingmall/product/service/ProductService.java
Labels: refactor

#70 refactor : Cart refactoring
  src/main/java/com/sparta/shoppingmall/cart/controller/CartController.java
  src/main/java/com/sparta/shoppingmall/cart/dto/CartProductRequest.java
  src/main/java/com/sparta/shoppingmall/cart/dto/CartProductResponse.java
  src/main/java/com/sparta/shoppingmall/cart/entity/Cart.java
  src/main/java/com/sparta/shoppingmall/cart/entity/CartProduct.java
  src/main/java/com/sparta/shoppingmall/cart/repository/CartProductRepository.java
  src/main/java/com/sparta/shoppingmall/cart/service/CartService.java
  src/main/java/com/sparta/shoppingmall/comment/entity/Comment.java
  src/main/java/com/sparta/shoppingmall/like/controller/LikesController.java
  src/main/java/com/sparta/shoppingmall/like/dto/LikesResponse.java
  src/main/java/com/sparta/shoppingmall/like/entity/Likes.java
  src/main/java/com/sparta/shoppingmall/like/service/LikesService.java
  src/main/java/com/sparta/shoppingmall/order/service/OrderGroupService.java
  src/main/java/com/sparta/shoppingmall/product/controller/ProductController.java
  src/main/java/com/sparta/shoppingmall/product/entity/Product.java
  src/main/java/com/sparta/shoppingmall/user/controller/UserController.java
Labels: refactor

#80 [FEARTUE] 백오피스 기능 생성
  src/main/java/com/sparta/shoppingmall/cart/entity/CartProduct.java
  src/main/java/com/sparta/shoppingmall/cart/service/CartService.java
  src/main/java/com/sparta/shoppingmall/config/SecurityConfig.java
  src/main/java/com/sparta/shoppingmall/product/controller/ProductController.java
  src/main/java/com/sparta/shoppingmall/product/entity/Product.java
  src/main/java/com/sparta/shoppingmall/product/entity/ProductStatus.java
  src/main/java/com/sparta/shoppingmall/product/repository/ProductRepository.java
  src/main/java/com/sparta/shoppingmall/product/service/ProductService.java
  src/main/java/com/sparta/shoppingmall/security/JwtAuthenticationFilter.java
  src/main/java/com/sparta/shoppingmall/user/controller/UserController.java
  src/main/java/com/sparta/shoppingmall/user/dto/AdminUpdateUserRequest.java
  src/main/java/com/sparta/shoppingmall/user/dto/AdminUserResponse.java
  src/main/java/com/sparta/shoppingmall/user/dto/EditPasswordRequestDTO.java
  src/main/java/com/sparta/shoppingmall/user/dto/EditProfileRequestDTO.java
  src/main/java/com/sparta/shoppingmall/user/dto/LoginRequestDTO.java
  src/main/java/com/sparta/shoppingmall/user/dto/SignupRequestDTO.java
  src/main/java/com/sparta/shoppingmall/user/dto/WithdrawRequestDTO.java
  src/main/java/com/sparta/shoppingmall/user/entity/User.java
  src/main/java/com/sparta/shoppingmall/user/entity/UserStatus.java
  src/main/java/com/sparta/shoppingmall/user/service/UserService.java
Labels: feature

#84 [FEATURE] Follow CRUD
  src/main/java/com/sparta/shoppingmall/config/SecurityConfig.java
  src/main/java/com/sparta/shoppingmall/follows/controller/FollowsController.java
  src/main/java/com/sparta/shoppingmall/follows/dto/FollowsResponse.java
  src/main/java/com/sparta/shoppingmall/follows/entity/Follows.java
  src/main/java/com/sparta/shoppingmall/follows/repository/FollowsRepository.java
  src/main/java/com/sparta/shoppingmall/follows/service/FollowsService.java
  src/main/java/com/sparta/shoppingmall/like/controller/LikesController.java
  src/main/java/com/sparta/shoppingmall/user/entity/User.java
  src/main/java/com/sparta/shoppingmall/user/service/UserService.java
Labels: feature

#85 refactor: #73- product-test
  api-test/product-test.http
  api-test/user-test.http
  src/main/java/com/sparta/shoppingmall/product/controller/ProductController.java
Labels: refactor
